trigger:
  - Deploy-teste
pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: "Build e Push para ACR"
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dotnetmssqlrm559982'
              repository: 'container-deploy'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest