trigger:
  - Deploy-teste

pool:
  vmImage: ubuntu-latest

stages:

  - stage: Build
    displayName: "Build e Push para ACR"
    jobs:
      - job: BuildAndPush
        steps:
          - task: Docker@2
            displayName: "Build da imagem"
            inputs:
              containerRegistry: "dotnetmssqlrm559982"
              repository:        "dotnetsql"
              command:           "build"
              Dockerfile:        "**/Dockerfile"
              tags: |
                $(Build.BuildId)
                latest
          - task: Docker@2
            displayName: "Push para ACR"
            inputs:
              containerRegistry: "dotnetmssqlrm559982"
              repository:        "dotnetsql"
              command:           "push"
              tags: |
                $(Build.BuildId)
                latest

  - stage: Deploy
    displayName: "Deploy no ACI"
    dependsOn: Build
    jobs:
      - job: DeployACI
        steps:
          - task: AzureCLI@2
            displayName: "Criar container no ACI"
            inputs:
              azureSubscription: "Azure for Students (18bb83d1-9d22-4924-99be-d308097ab484)"
              scriptType:        "bash"
              scriptLocation:    "inlineScript"
              inlineScript: |
                az container delete \
                  --resource-group rg-azuredevops-ecoorbit \
                  --name dotnetmssqlrm559982 \
                  --yes

                az container create \
                  --resource-group rg-azuredevops-ecoorbit \
                  --name dotnetmssqlrm559982 \
                  --image dotnetmssqlrm559982.azurecr.io/dotnetsql:latest \
                  --cpu 2 \
                  --memory 2 \
                  --os-type Linux \
                  --registry-login-server dotnetmssqlrm559982.azurecr.io \
                  --registry-username dotnetmssqlrm559982 \
                  --registry-password "VejwYMuBTL7HUVWVRDsykTSxoJk3v5GqyfbBgEWRaJ66ppaRLei0JQQJ99CFACPV0roEqg7NAAACAZCRTzsA" \
                  --dns-name-label dotnetmssqlrm559982 \
                  --restart-policy Always \
                  --ports 80 
                  
